services:
  - type: web
    name: ecommerce-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: MONGODB_URI
        value: your_mongodb_atlas_connection_string_here
    plan: free